// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Medical

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void HistoryAnim_Animation(lv_obj_t * TargetObject, int delay);
void HistoryAnimOff_Animation(lv_obj_t * TargetObject, int delay);
void HeartAnim_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Medical_Screen
void ui_Medical_Screen_screen_init(void);
lv_obj_t * ui_Medical_Screen;
lv_obj_t * ui_Panel_History;
lv_obj_t * ui_Label_History;
lv_obj_t * ui_Label_YBP;
lv_obj_t * ui_Panel_History_Content;
lv_obj_t * ui_Panel_Today;
lv_obj_t * ui_Label_Today;
lv_obj_t * ui_Panel_Today_Content_1;
lv_obj_t * ui_Label_List_1;
lv_obj_t * ui_Label_Date_1;
lv_obj_t * ui_Label_List_1_copy;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Panel_Today_Content_2;
lv_obj_t * ui_Label_List_2;
lv_obj_t * ui_Label_Date_2;
lv_obj_t * ui_Label_List_Pul_2;
lv_obj_t * ui_IMG_Heart_Small_1;
lv_obj_t * ui_Panel_Today_Content_3;
lv_obj_t * ui_Label_List_3;
lv_obj_t * ui_Label_Date_3;
lv_obj_t * ui_Label_List_Pul_3;
lv_obj_t * ui_IMG_Heart_Small_2;
lv_obj_t * ui_Panel_Yesterday;
lv_obj_t * ui_Label_Yesterday;
lv_obj_t * ui_Panel_Today_Content_5;
lv_obj_t * ui_Label_List_5;
lv_obj_t * ui_Label_Date_5;
lv_obj_t * ui_Label_List_Pul_5;
lv_obj_t * ui_IMG_Heart_Small_5;
lv_obj_t * ui_Panel_Today_Content_6;
lv_obj_t * ui_Label_List_6;
lv_obj_t * ui_Label_Date_6;
lv_obj_t * ui_Label_List_Pul_6;
lv_obj_t * ui_IMG_Heart_Small_6;
lv_obj_t * ui_Panel_Today_Content_7;
lv_obj_t * ui_Label_List_7;
lv_obj_t * ui_Label_Date_7;
lv_obj_t * ui_Label_List_Pul_7;
lv_obj_t * ui_IMG_Heart_Small_7;
void ui_event_Panel_S1(lv_event_t * e);
lv_obj_t * ui_Panel_S1;
void ui_event_BTN_History(lv_event_t * e);
lv_obj_t * ui_BTN_History;
lv_obj_t * ui_Label_Date;
lv_obj_t * ui_Label_Hour;
lv_obj_t * ui_IMG_Battery;
lv_obj_t * ui_IMG_Bluetooth;
lv_obj_t * ui_Label_Battey;
lv_obj_t * ui_Panel_Content;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Line_1;
lv_obj_t * ui_Line_2;
lv_obj_t * ui_Line_3;
lv_obj_t * ui_Line_4;
lv_obj_t * ui_IMG_Line_1;
lv_obj_t * ui_IMG_Line_2;
lv_obj_t * ui_IMG_Line_3;
lv_obj_t * ui_Number_SYS;
lv_obj_t * ui_Number_DIA;
lv_obj_t * ui_Number_PUL;
lv_obj_t * ui_Label_SYS;
lv_obj_t * ui_Label_mmHg_1;
lv_obj_t * ui_Label_DIA;
lv_obj_t * ui_Label_mmHg_2;
lv_obj_t * ui_Label_PUL;
lv_obj_t * ui_Label_mmHg_3;
lv_obj_t * ui_IMG_Heart;
lv_obj_t * ui_Panel_Bottom;
lv_obj_t * ui_IMG_BTN_Bg;
void ui_event_BTN_Power(lv_event_t * e);
lv_obj_t * ui_BTN_Power;
lv_obj_t * ui_Switch_Sound;
lv_obj_t * ui_Label_Sound;
void ui_event_Switch_Bluetooth(lv_event_t * e);
lv_obj_t * ui_Switch_Bluetooth;
lv_obj_t * ui_Label_Bluetooth;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void HistoryAnim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 200);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
void HistoryAnimOff_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 200, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void HeartAnim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_0, 400, 256);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 200);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_1, 400, 256);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 500);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);
    ui_anim_user_data_t * PropertyAnimation_2_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_2_user_data->target = TargetObject;
    PropertyAnimation_2_user_data->val = -1;
    lv_anim_t PropertyAnimation_2;
    lv_anim_init(&PropertyAnimation_2);
    lv_anim_set_time(&PropertyAnimation_2, 200);
    lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_2, 400, 256);
    lv_anim_set_path_cb(&PropertyAnimation_2, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_2, delay + 1000);
    lv_anim_set_deleted_cb(&PropertyAnimation_2, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_2, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
    lv_anim_set_early_apply(&PropertyAnimation_2, false);
    lv_anim_start(&PropertyAnimation_2);
    ui_anim_user_data_t * PropertyAnimation_3_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_3_user_data->target = TargetObject;
    PropertyAnimation_3_user_data->val = -1;
    lv_anim_t PropertyAnimation_3;
    lv_anim_init(&PropertyAnimation_3);
    lv_anim_set_time(&PropertyAnimation_3, 200);
    lv_anim_set_user_data(&PropertyAnimation_3, PropertyAnimation_3_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_3, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_3, 400, 256);
    lv_anim_set_path_cb(&PropertyAnimation_3, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_3, delay + 1500);
    lv_anim_set_deleted_cb(&PropertyAnimation_3, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_3, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_3, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_3, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_3, 0);
    lv_anim_set_early_apply(&PropertyAnimation_3, false);
    lv_anim_start(&PropertyAnimation_3);
    ui_anim_user_data_t * PropertyAnimation_4_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_4_user_data->target = TargetObject;
    PropertyAnimation_4_user_data->val = -1;
    lv_anim_t PropertyAnimation_4;
    lv_anim_init(&PropertyAnimation_4);
    lv_anim_set_time(&PropertyAnimation_4, 200);
    lv_anim_set_user_data(&PropertyAnimation_4, PropertyAnimation_4_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_4, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_4, 400, 256);
    lv_anim_set_path_cb(&PropertyAnimation_4, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_4, delay + 2000);
    lv_anim_set_deleted_cb(&PropertyAnimation_4, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_4, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_4, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_4, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_4, 0);
    lv_anim_set_early_apply(&PropertyAnimation_4, false);
    lv_anim_start(&PropertyAnimation_4);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Panel_S1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HistoryAnimOff_Animation(ui_Panel_S1, 0);
        _ui_flag_modify(ui_Panel_S1, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_BTN_History, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_BTN_History(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        HistoryAnim_Animation(ui_Panel_S1, 0);
        _ui_flag_modify(ui_BTN_History, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Panel_S1, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_BTN_Power(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        HeartAnim_Animation(ui_IMG_Heart, 0);
    }
}
void ui_event_Switch_Bluetooth(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_IMG_Bluetooth, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Medical_Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Medical_Screen);
}
